import { useState } from 'react';

export interface AnalysisResult {
  doctorAnalysis: string;
  laymanSummary: string;
}

export const useGemini = () => {
  const [analysis, setAnalysis] = useState<string>('');
  const [summary, setSummary] = useState<string>('');
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string | null>(null);

  const generateAnalysis = async (patientData: string, file: File | null, useGrounding: boolean) => {
    setIsLoading(true);
    setError(null);
    
    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    try {
      // Mock response
      if (patientData.trim() === '' && !file) {
        throw new Error('Please provide patient data or upload a medical scan/report.');
      }
      
      const mockAnalysis = `
Medical Analysis Report

Patient Presentation:
${patientData.substring(0, 100)}${patientData.length > 100 ? '...' : ''}

Findings:
- Based on the provided information, the patient appears to present with symptoms consistent with seasonal allergies.
- Key indicators include nasal congestion, itchy eyes, and sneezing.
- Differential diagnoses to consider: allergic rhinitis, common cold, sinusitis.

Recommendations:
- Recommend further diagnostic testing including allergy panel.
- Consider consultation with allergist for comprehensive evaluation.
- Monitor for changes in respiratory symptoms.

Additional Notes:
- Patient history suggests potential risk factors for environmental allergies.
- Current presentation may be complicated by weather changes.

This analysis is generated by AI and should be verified by a qualified healthcare professional before making clinical decisions.
`;

      const mockSummary = `
In simple terms, your symptoms might be related to seasonal allergies. 

What this means:
- Your symptoms like congestion, itchy eyes, and sneezing are common with this type of condition
- This is typically caused by environmental factors like pollen or dust
- Many people experience similar symptoms during certain seasons

Next steps that your doctor might recommend:
- Some tests to confirm what specific allergens affect you
- Possibly some medication to help with your symptoms
- Follow-up visits to track your progress

Remember, this is just a computer-generated summary to help you understand medical terms. Your doctor will provide you with accurate information specific to your situation.
`;

      setAnalysis(mockAnalysis);
      setSummary(mockSummary);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unknown error occurred');
    } finally {
      setIsLoading(false);
    }
  };

  return { generateAnalysis, analysis, summary, isLoading, error };
};

export default useGemini;
